cmake_minimum_required(VERSION 3.8)
project(traversability_mapping)
if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(nav_msgs REQUIRED)
find_package(px4_msgs REQUIRED)
find_package(PkgConfig REQUIRED)
pkg_check_modules(GZ_TRANSPORT REQUIRED IMPORTED_TARGET gz-transport13)
pkg_check_modules(GZ_MSGS REQUIRED IMPORTED_TARGET gz-msgs10)

add_executable(traversability_mapper src/traversability_mapper.cpp)
ament_target_dependencies(traversability_mapper rclcpp nav_msgs px4_msgs)
target_link_libraries(traversability_mapper PkgConfig::GZ_TRANSPORT PkgConfig::GZ_MSGS)

install(TARGETS traversability_mapper DESTINATION lib/${PROJECT_NAME})
ament_package()
