cmake_minimum_required(VERSION 3.8)
project(ugv_control)
if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(nav_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(PkgConfig REQUIRED)
pkg_check_modules(GZ_TRANSPORT REQUIRED IMPORTED_TARGET gz-transport13)
pkg_check_modules(GZ_MSGS REQUIRED IMPORTED_TARGET gz-msgs10)

add_executable(goal_controller src/goal_controller.cpp)
ament_target_dependencies(goal_controller rclcpp geometry_msgs nav_msgs)
target_link_libraries(goal_controller PkgConfig::GZ_TRANSPORT PkgConfig::GZ_MSGS)

install(TARGETS goal_controller DESTINATION lib/${PROJECT_NAME})
ament_package()
